Features/map
SleekOrg/orderahead-user-app pull request #11
Opened 2021-04-11 06:41 UTC by aryansingh02

2021-04-12 20:46 UTC, teamSleek requested changes

2021-04-12 20:46 UTC, teamSleek commented on .eslintrc
> +    // some problem with react project
be more descriptive?

2021-04-12 20:46 UTC, teamSleek commented on .eslintrc
> +      "warn",
this seems like a legit check. Remove all unnecessary dependencies. Why tone down the checks?

2021-04-12 20:46 UTC, teamSleek commented on public/index.html
> +    <div id="map"></div>
Add comment. Why do we need this? And do we need this `div` in all the componenets

2021-04-12 20:46 UTC, teamSleek commented on src/App.scss
> +.MuiInputBase-root .InputBase-adornedStart .MuiInputBase-adornedEnd {
scope these styling in your own components or use `border` attribute instead of custom styling.

https://material-ui.com/system/borders/

2021-04-12 20:46 UTC, teamSleek commented on src/features/event/AutoCompleteService.tsx
> +    fetch(
refractor this function in a separate module e.g. MapUtils.ts

2021-04-12 20:46 UTC, teamSleek commented on src/utils.tsx
> +const findDetails = (
move all Map related functions together in a separate MapUtil.ts file

2021-04-12 20:46 UTC, teamSleek commented on public/index.html
> +
Change "Times Square, Manhattan.." with actual location that was selected?

<img width="1725" alt="Screen Shot 2021-04-12 at 1 41 00 PM" src="https://user-images.githubusercontent.com/61997705/114458970-c22b1300-9b94-11eb-9b35-f40b07dd1030.png">

2021-04-12 20:46 UTC, teamSleek commented on src/App.scss
> +
Blank map until the location is selected. Set SF to be the default location.
<img width="1718" alt="Screen Shot 2021-04-12 at 1 42 06 PM" src="https://user-images.githubusercontent.com/61997705/114459074-e555c280-9b94-11eb-9b94-3423576933a8.png">

2021-04-12 20:46 UTC, teamSleek commented on src/App.tsx
> +import MapView from './features/event/MapView';
What is this gray bar at the top of header?
<img width="1742" alt="Screen Shot 2021-04-12 at 1 42 46 PM" src="https://user-images.githubusercontent.com/61997705/114459125-f9012900-9b94-11eb-9e1c-e282b24b5fe0.png">

2021-04-12 20:46 UTC, teamSleek commented on src/components/BottomNavigationBar.tsx
> +          props.history.push('/map');
Have we implemented this tile as part of the PR as well? If yes, then can you add locations of a few stalls in demo data and how it as an example?

<img width="464" alt="Screen Shot 2021-04-12 at 1 43 58 PM" src="https://user-images.githubusercontent.com/61997705/114459269-25b54080-9b95-11eb-94e1-0ad934036ce2.png">

2021-04-13 04:17 UTC, aryansingh02 commented on src/App.tsx
> +import MapView from './features/event/MapView';
refresh the page

2021-04-13 04:26 UTC, aryansingh02 commented on src/utils.tsx
> +const findDetails = (
done

2021-04-13 04:36 UTC, aryansingh02 commented on src/features/event/AutoCompleteService.tsx
> +    fetch(
this is tightly coupled with the component, component listens to if and when has google maps loaded then calls the autocomplete service. Moreover it uses React.memo for performance reason. 

I copied the Autocomplete example from material ui website, forcefully refactoring will cause more confusion.

2021-04-13 04:37 UTC, aryansingh02 commented on src/components/BottomNavigationBar.tsx
> +          props.history.push('/map');
it's not implemented as part of this pr

2021-04-14 02:16 UTC, teamSleek commented
@aryansingh02 did you forget to push the changes? I see the last commit 3 days ago and many of the bugs that you have resolved are not fixed.

2021-04-14 02:20 UTC, aryansingh02 commented on .eslintrc
> +      "warn",
typescript keeps failing this check even if i installed a package properly

2021-04-14 02:37 UTC, aryansingh02 commented on src/App.scss
> +.MuiInputBase-root .InputBase-adornedStart .MuiInputBase-adornedEnd {
fixed

2021-04-14 02:56 UTC, teamSleek requested changes
Changing map location on desktop doesn change the map

steps
* open http://localhost:3000/cart
* Change location to new york
* Map will remain at SF

This is not an issue on Mobile

2021-04-14 03:13 UTC, aryansingh02 commented
> @aryansingh02 did you forget to push the changes? I see the last commit 3 days ago and many of the bugs that you have resolved are not fixed.

![image](https://user-images.githubusercontent.com/67533555/114649120-c0e10f80-9c94-11eb-89f7-817a960d0d1c.png)

2021-04-14 03:44 UTC, aryansingh02 commented
> Changing map location on desktop doesn change the map
> 
> steps
> 
> * open http://localhost:3000/cart
> * Change location to new york
> * Map will remain at SF
> 
> This is not an issue on Mobile


Uploading Screen Recording 2021-04-14 at 9.12.00 AM.mov…

2021-04-14 05:45 UTC, merged