feat(NewOrderAheadApp/Menu Item Screen):Added Menu Item screen for new order ahead app.
SleekOrg/orderahead-user-app pull request #12
Opened 2021-04-12 05:54 UTC by dabralyogesh12

Issues: fixes https://github.com/SleekOrg/tracker/issues/273
feat(NewOrderAheadApp/Menu Item Screen): Added Menu Item screen for the new order-ahead app.
Description: Added the layout for the menu item screen.
Verification: Tested locally.

2021-04-12 22:31 UTC, teamSleek requested changes

2021-04-12 22:31 UTC, teamSleek commented on src/App.tsx
> +import { MenuItem } from './features/stall/MenuItem';
Show zero where it is zero.

<img width="293" alt="Screen Shot 2021-04-12 at 3 17 03 PM" src="https://user-images.githubusercontent.com/61997705/114469499-243e4500-9ba2-11eb-8f31-c5636592220e.png">

2021-04-12 22:31 UTC, teamSleek commented on src/features/stall/MenuItem.tsx
> +            <AboutItem details="Free range egg, Cumberland sausage, and beechwood smoked bacon with Heinz tomato ketchup & béchamel sauce in a barmarked tortilla wrap." />
Font seems off

2021-04-12 22:31 UTC, teamSleek commented on src/features/stall/MenuItem.tsx
> +            <AddDelete />
Alignment is off
<img width="462" alt="Screen Shot 2021-04-12 at 3 22 29 PM" src="https://user-images.githubusercontent.com/61997705/114470080-1dfc9880-9ba3-11eb-952c-2ab5b7aab3b7.png">

2021-04-12 22:31 UTC, teamSleek commented on src/features/stall/MenuItem.tsx
> +          itemName="Ultimate Breakfast Wrap"
`Ultimate Breakfast Wrap` grid seems off. If Figma the name is in 2 lines and your demo shows it in 3 lines

2021-04-12 22:31 UTC, teamSleek commented on src/features/stall/MenuItem.tsx
> +              <Currency quantity={20.0} currency="USD" />
missing space with ` -`

2021-04-12 22:31 UTC, teamSleek commented on src/features/stall/MenuItem.tsx
> +        </Grid>
Alignment off
<img width="1618" alt="Screen Shot 2021-04-12 at 3 27 25 PM" src="https://user-images.githubusercontent.com/61997705/114470361-9bc0a400-9ba3-11eb-8aa8-e085a59fdba6.png">

2021-04-12 22:31 UTC, teamSleek commented on src/features/stall/MenuItem.tsx
> +            direction="column"
Add markers such as 
* `* Required`
* `minimum 2`
* `maximum 6`

2021-04-12 22:31 UTC, teamSleek commented on src/features/stall/Variations.tsx
> +    console.log(newChecked);
remove log or convert to debug

2021-04-13 02:56 UTC, dabralyogesh12 commented on src/features/stall/MenuItem.tsx
> +          itemName="Ultimate Breakfast Wrap"
Yes, that because of screen width.

2021-04-13 04:08 UTC, dabralyogesh12 commented on src/App.tsx
> +import { MenuItem } from './features/stall/MenuItem';
Done, updated PR.

2021-04-13 04:09 UTC, dabralyogesh12 commented on src/features/stall/MenuItem.tsx
> +            <AboutItem details="Free range egg, Cumberland sausage, and beechwood smoked bacon with Heinz tomato ketchup & béchamel sauce in a barmarked tortilla wrap." />
It's the same as in Figma.

2021-04-13 04:09 UTC, dabralyogesh12 commented on src/features/stall/MenuItem.tsx
> +            <AddDelete />
Done, updated PR.

2021-04-13 04:09 UTC, dabralyogesh12 commented on src/features/stall/MenuItem.tsx
> +              <Currency quantity={20.0} currency="USD" />
Done, updated PR.

2021-04-13 04:09 UTC, dabralyogesh12 commented on src/features/stall/MenuItem.tsx
> +        </Grid>
Done, updated PR.

2021-04-13 04:09 UTC, dabralyogesh12 commented on src/features/stall/MenuItem.tsx
> +            direction="column"
Will add that during integration.

2021-04-13 04:10 UTC, dabralyogesh12 commented on src/features/stall/Variations.tsx
> +    console.log(newChecked);
Done, updated PR.

2021-04-14 16:58 UTC, merged