feat(NewOrderAheadApp/Integration): Integrated the categories scroll with Stall Menu screen.
SleekOrg/orderahead-user-app pull request #13
Opened 2021-04-12 17:05 UTC by dabralyogesh12

Issues: fixes https://github.com/SleekOrg/tracker/issues/304
feat(NewOrderAheadApp/Integration): Integrated the categories scroll with Stall Menu screen.
Description: Integrated Categories Scroll component with stall menu screen.
Verification: Tested manually.

2021-04-12 21:49 UTC, teamSleek requested changes

2021-04-12 21:49 UTC, teamSleek commented on src/features/stall/ItemCard.tsx
> +import { Theme, createStyles, makeStyles } from '@material-ui/core/styles';
Categories flying off to the left.

<img width="1725" alt="Screen Shot 2021-04-12 at 2 49 17 PM" src="https://user-images.githubusercontent.com/61997705/114467115-446c0500-9b9e-11eb-9c90-d0c604029518.png">

2021-04-13 02:53 UTC, dabralyogesh12 commented on src/features/stall/ItemCard.tsx
> +import { Theme, createStyles, makeStyles } from '@material-ui/core/styles';
Yeah, have talked to Aryan regarding this, centralizing the categories will be done in the Category component itself.

2021-04-13 17:29 UTC, dabralyogesh12 commented on src/features/stall/ItemCard.tsx
> +import { Theme, createStyles, makeStyles } from '@material-ui/core/styles';
Done, updated PR.

2021-04-13 23:25 UTC, merged