Features/event
SleekOrg/orderahead-user-app pull request #4
Opened 2021-03-28 21:37 UTC by aryansingh02

description: adding desktop compatiblity in separate pr. Custom font with roboto took lot of reading and effort.
verification: verified the designs and components manually

2021-03-29 19:39 UTC, teamSleek requested changes

2021-03-29 19:39 UTC, teamSleek commented on .eslintrc
> +    "@typescript-eslint/quotes": "off",
add comments justifying the relaxations in the eslint rules.

2021-03-29 19:39 UTC, teamSleek commented on .eslintrc
> +    "react/static-property-placement": "off",
Category icon spacing is off on desktop. It scales with the scaling from mobile < tablet < desktop
![Uploading Screen Shot 2021-03-29 at 12.07.01 PM.png…]()

2021-03-29 19:39 UTC, teamSleek commented on package.json
> +    "@types/google-map-react": "^2.1.0",
Since this is a demo that will be exposed outside soon, Can you use the dummy content in the Figma https://www.figma.com/file/2nDIQD8dzD8PLbpBLl1I8K/Sleek---Skip-The-Line--App?node-id=0%3A1 ?

<img width="501" alt="Screen Shot 2021-03-29 at 12 08 56 PM" src="https://user-images.githubusercontent.com/61997705/112887032-8c136c80-9087-11eb-9e32-3451633484c0.png">

2021-03-29 19:39 UTC, teamSleek commented on public/img/cart_icon.svg
> +<svg width="16" height="17" viewBox="0 0 16 17" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
Font and icon sizing seems off in a couple of the place. See all the highlighted things.

<img width="1192" alt="Screen Shot 2021-03-29 at 12 12 58 PM" src="https://user-images.githubusercontent.com/61997705/112887853-823e3900-9088-11eb-9242-1913065eef23.png">

2021-03-29 19:39 UTC, teamSleek commented on public/img/map_icon.svg
> +<svg width="16" height="17" viewBox="0 0 16 17" fill="none" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
Spacing is off on desktop. See all the red lines indicating the spacing.

<img width="1491" alt="Screen Shot 2021-03-29 at 12 16 58 PM" src="https://user-images.githubusercontent.com/61997705/112888218-f11b9200-9088-11eb-8614-84b872e7ad77.png">

2021-03-29 19:39 UTC, teamSleek commented on public/index.html
> +    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
Where is the image behind the location selector on the desktop.

<img width="570" alt="Screen Shot 2021-03-29 at 12 19 49 PM" src="https://user-images.githubusercontent.com/61997705/112888346-14ded800-9089-11eb-8129-75501729cadf.png">

2021-03-29 19:39 UTC, teamSleek commented on src/App.scss
> +html {
Hamburger menu missing

<img width="358" alt="Screen Shot 2021-03-29 at 12 21 05 PM" src="https://user-images.githubusercontent.com/61997705/112888486-422b8600-9089-11eb-98a5-370082031e26.png">

2021-03-29 19:39 UTC, teamSleek commented on src/Typography.jsx
> +import { Typography as MuiTypography, withStyles } from '@material-ui/core';
Top spacing missing

<img width="515" alt="Screen Shot 2021-03-29 at 12 21 53 PM" src="https://user-images.githubusercontent.com/61997705/112888635-730bbb00-9089-11eb-9b98-2c42e50ea3bf.png">

2021-03-29 19:39 UTC, teamSleek commented on src/Typography.jsx
> +import { Typography as MuiTypography, withStyles } from '@material-ui/core';
Is it possible to change grey to white as it is the case in Figma? 

<img width="1643" alt="Screen Shot 2021-03-29 at 12 23 44 PM" src="https://user-images.githubusercontent.com/61997705/112888762-9d5d7880-9089-11eb-8446-108cadb7f27b.png">

2021-03-29 19:39 UTC, teamSleek commented on src/Typography.jsx
> +    >
I do not see the on-hover effect of purple as shown below in the Figma

<img width="409" alt="Screen Shot 2021-03-29 at 12 24 26 PM" src="https://user-images.githubusercontent.com/61997705/112888844-b82fed00-9089-11eb-83e1-607df140fe84.png">

2021-03-29 19:39 UTC, teamSleek commented on src/Typography.jsx
> +import { Typography as MuiTypography, withStyles } from '@material-ui/core';
Star should be filled depending on the percentage of 4.5/5 here. Is that the case?
<img width="61" alt="Screen Shot 2021-03-29 at 12 29 00 PM" src="https://user-images.githubusercontent.com/61997705/112889342-5a4fd500-908a-11eb-93bb-5c1703b7def7.png">

2021-03-29 19:39 UTC, teamSleek commented on src/components/BottomNavigationHoc.tsx
> +      {window.innerWidth > 1280 ? (
create a util function for `window.innerWidth > 1280` as it seems like the mobile vs desktop detection logic and we want to use the common logic in most of the places possile.

2021-03-29 19:39 UTC, teamSleek commented on src/features/event/DemoEvent.tsx
> +  eventContainerRef: React.RefObject<HTMLInputElement>;
rename this from DemoEvent to Event ?

2021-03-29 19:39 UTC, teamSleek commented on src/features/event/DesktopHeader.tsx
> +export default function DesktopHeader() {
why name it `DesktopHeader`? do we use a different one for mobile? if yes, then why?

2021-03-29 19:39 UTC, teamSleek commented on src/features/event/EventMap.tsx
> +        bootstrapURLKeys={{ key: process.env.REACT_APP_GOOGLE_KEY || '' }}
create a config.ts file similar to https://github.com/SleekOrg/localty-frontend/blob/main/src/config.tsx and use config variables from there.

2021-03-29 19:39 UTC, teamSleek commented on src/features/event/EventMap.tsx
> +      </GoogleMapReact>
StallCard image should have rounded edges. Compare with figma mocks.
<img width="384" alt="Screen Shot 2021-03-29 at 12 34 17 PM" src="https://user-images.githubusercontent.com/61997705/112889900-16a99b00-908b-11eb-8ab4-d353e750b654.png">

2021-03-29 19:39 UTC, teamSleek commented on src/features/event/PlacesFilter.tsx
> +import MenuItem from '@material-ui/core/MenuItem';
Set location of the map to be on San Francisco.

<img width="1141" alt="Screen Shot 2021-03-29 at 12 35 04 PM" src="https://user-images.githubusercontent.com/61997705/112890017-3640c380-908b-11eb-9398-47b0b15e69c2.png">

2021-03-29 19:39 UTC, teamSleek commented on package.json
> +    "react-icons": "^4.2.0",
I think that you can safely delete all the images in `public/img/auto_gen/` directory

2021-04-04 09:56 UTC, aryansingh02 commented on src/features/event/DesktopHeader.tsx
> +export default function DesktopHeader() {
because positioning and stuff is different and hard to achieve by just being responsive

2021-04-05 04:03 UTC, teamSleek commented on .eslintrc
> +    "@typescript-eslint/quotes": "off",
@aryansingh02 how is this comment resolved? can you explain?

2021-04-05 04:17 UTC, teamSleek requested changes

2021-04-05 04:17 UTC, teamSleek commented on src/utils.tsx
> +export const GenerateExpenseLevel = (expenseLevel: number) => {
See all the red highlighted issues in desktop. Make sure that you "verify" things by matching them with Figma once.

![Screen Shot 2021-04-04 at 9 09 18 PM](https://user-images.githubusercontent.com/61997705/113536220-6a841a80-958a-11eb-975d-fd0e0bd4c8df.png)

2021-04-05 04:17 UTC, teamSleek commented on src/utils.tsx
> +  <span
Size of icons seem off
![Screen Shot 2021-04-04 at 9 13 57 PM](https://user-images.githubusercontent.com/61997705/113536420-f1d18e00-958a-11eb-8ba4-359df2150306.png)

2021-04-05 04:17 UTC, teamSleek commented on src/utils.tsx
> +    }}
Can you add some more cards? I want to test the scroll behaviour of cards. Just replicate the cards by adding them twice using test data
![Screen Shot 2021-04-04 at 9 16 12 PM](https://user-images.githubusercontent.com/61997705/113536446-00b84080-958b-11eb-8300-ae7c8595ab23.png)

2021-04-05 04:32 UTC, aryansingh02 commented on .eslintrc
> +    "@typescript-eslint/quotes": "off",
explained

2021-04-05 04:39 UTC, aryansingh02 commented on src/utils.tsx
> +export const GenerateExpenseLevel = (expenseLevel: number) => {
all these have been fixed already, i double checked. right now. 
![image](https://user-images.githubusercontent.com/67533555/113537639-20049d00-958e-11eb-8747-651bc1fbea62.png)

2021-04-05 07:37 UTC, teamSleek commented on src/utils.tsx
> +export const GenerateExpenseLevel = (expenseLevel: number) => {
They were fixed on mobile but not on the desktop for me.

2021-04-05 07:37 UTC, teamSleek commented
Fix the conflict as well

2021-04-05 20:11 UTC, merged