feat(NewOrderAhead/Screens Layout): Completed layout of Added to Cart, Order Sent screen and Stall Menu Screen. Added the Loading component. Partially completed Order Status screen."
SleekOrg/orderahead-user-app pull request #5
Opened 2021-03-30 15:27 UTC by dabralyogesh12

Issues: fixes https://github.com/SleekOrg/tracker/issues/297, https://github.com/SleekOrg/tracker/issues/295, https://github.com/SleekOrg/tracker/issues/289, https://github.com/SleekOrg/tracker/issues/272
feat(NewOrderAhead/Screens Layout): Completed layout of Added to Cart, Order Sent screen, and Stall Menu Screen. Added the Loading component. Partially completed Order Status screen."
Description: Added the layouts for different screens. On the stall menu page, there are few things left like integration of the category menu and an overlay. Order Status screen is half left.
Verification: Ran the pages locally both on desktop and mobile.

2021-03-30 20:42 UTC, teamSleek requested changes
Make sure that you compare your code with Figma once.

2021-03-30 20:42 UTC, teamSleek commented on package.json
> +  "name": "OrderAhead",
2 and 54 are time not dollar values.

<img width="418" alt="Screen Shot 2021-03-30 at 1 10 42 PM" src="https://user-images.githubusercontent.com/61997705/113050199-6a82b580-9159-11eb-851a-0a2c3c7cab74.png">

2021-03-30 20:42 UTC, teamSleek commented on package.json
> +    "clsx": "^1.1.1",
Font sizes seems larger than those in Figma
<img width="355" alt="Screen Shot 2021-03-30 at 1 12 39 PM" src="https://user-images.githubusercontent.com/61997705/113050376-9dc54480-9159-11eb-9caf-62f4c5f722bd.png">

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/StallMenu.tsx
> +const useStyles = makeStyles((theme: Theme) =>
The entire top row on the bottom part of the image seems to be missing. The one distance, start rating, categories, $$$, etc.
<img width="496" alt="Screen Shot 2021-03-30 at 1 10 48 PM" src="https://user-images.githubusercontent.com/61997705/113050452-b3d30500-9159-11eb-8bf2-e05889799d6a.png">

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/StallMenu.tsx
> +    },
Padding is off. Red lines show larger than expected padding and blue line shows smaller than expected padding.

<img width="512" alt="Screen Shot 2021-03-30 at 1 14 14 PM" src="https://user-images.githubusercontent.com/61997705/113050732-057b8f80-915a-11eb-97a2-3de246008e47.png">

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/StallMenu.tsx
> +      marginTop: theme.spacing(6),
top padding to $6 seems off

<img width="358" alt="Screen Shot 2021-03-30 at 1 16 57 PM" src="https://user-images.githubusercontent.com/61997705/113050944-4b385800-915a-11eb-9aba-f942c5dc072b.png">

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/StallMenu.tsx
> +);
Bottom shadow seems off. Your card seems more 3D than the one in figma.

<img width="340" alt="Screen Shot 2021-03-30 at 1 18 31 PM" src="https://user-images.githubusercontent.com/61997705/113051073-6e630780-915a-11eb-8312-6cb470179e96.png">
<img width="333" alt="Screen Shot 2021-03-30 at 1 18 39 PM" src="https://user-images.githubusercontent.com/61997705/113051095-73c05200-915a-11eb-9d4b-f376417ddbb8.png">

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/StallMenu.tsx
> +    },
Create a follow up bug for category menu
<img width="357" alt="Screen Shot 2021-03-30 at 1 19 23 PM" src="https://user-images.githubusercontent.com/61997705/113051188-8d619980-915a-11eb-81ec-0d4f7b571321.png">

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/StallMenu.tsx
> +);
Bottom shadow on this card seems off too. Your cards are looking much more 3D

Your thing:
<img width="461" alt="Screen Shot 2021-03-30 at 1 19 53 PM" src="https://user-images.githubusercontent.com/61997705/113051241-9fdbd300-915a-11eb-865a-509a74fef02c.png">

Figma:
<img width="436" alt="Screen Shot 2021-03-30 at 1 20 37 PM" src="https://user-images.githubusercontent.com/61997705/113051357-b97d1a80-915a-11eb-83c0-8d762c095af1.png">

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/StallMenu.tsx
> +export const StallMenu = () => {
Color and styling for "2 min Skip the line" seems off too

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/StallMenu.tsx
> +  React.useEffect(() => {
Back button missing 

<img width="414" alt="Screen Shot 2021-03-30 at 1 21 41 PM" src="https://user-images.githubusercontent.com/61997705/113051566-f812d500-915a-11eb-909e-b7b51f533150.png">

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/StallMenu.tsx
> +    data.menu.menuItems.map((item) =>
Card onhover highlight effect seems missing.
<img width="542" alt="Screen Shot 2021-03-30 at 1 23 13 PM" src="https://user-images.githubusercontent.com/61997705/113051663-17116700-915b-11eb-8e51-5e4b70f901c2.png">

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/StallMenu.tsx
> +  }, []);
Extra padding
<img width="1750" alt="Screen Shot 2021-03-30 at 1 24 35 PM" src="https://user-images.githubusercontent.com/61997705/113051924-648dd400-915b-11eb-9b79-584a02113313.png">

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/StallSummary.tsx
> +export const StallSummary = (props: IProps) => {
Can you use the actual images in the Figma as it will make things look better for the demo?

<img width="1577" alt="Screen Shot 2021-03-30 at 1 26 08 PM" src="https://user-images.githubusercontent.com/61997705/113052021-7ff8df00-915b-11eb-8ca7-33ef3b0bbc9c.png">

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/AddedToCart.tsx
> +export default function AddedToCart() {
Font styling seems off

<img width="359" alt="Screen Shot 2021-03-30 at 1 27 47 PM" src="https://user-images.githubusercontent.com/61997705/113052224-b9c9e580-915b-11eb-9ae9-b414efb275e7.png">

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/OrderSent.tsx
> +import useMediaQuery from '@material-ui/core/useMediaQuery';
Size of the white box looks off
<img width="477" alt="Screen Shot 2021-03-30 at 1 28 47 PM" src="https://user-images.githubusercontent.com/61997705/113052370-e4b43980-915b-11eb-9516-9abb9ece260c.png">

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/OrderSent.tsx
> +import Dialog from '@material-ui/core/Dialog';
Font and outline should be using primary color of the theme
<img width="374" alt="Screen Shot 2021-03-30 at 1 29 35 PM" src="https://user-images.githubusercontent.com/61997705/113052433-fac1fa00-915b-11eb-9c16-7e1875e0cc7e.png">

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/OrderSent.tsx
> +} from '@material-ui/core/styles';
Spacing off <img width="550" alt="Screen Shot 2021-03-30 at 1 30 02 PM" src="https://user-images.githubusercontent.com/61997705/113053135-cb5fbd00-915c-11eb-8aa7-fba63181601e.png">

2021-03-30 20:42 UTC, teamSleek commented on src/components/loadingSlice.tsx
> +const landingSlice = createSlice({
where is this used?

2021-03-30 20:42 UTC, teamSleek commented on src/features/stall/OrderStatus.tsx
> +export default function OrderStatus() {
is this a work in progress?

2021-03-31 16:09 UTC, dabralyogesh12 commented on src/features/stall/OrderStatus.tsx
> +export default function OrderStatus() {
Yes, it is for the Order Status screen.

2021-03-31 16:09 UTC, dabralyogesh12 commented on src/components/loadingSlice.tsx
> +const landingSlice = createSlice({
Is not used yet, will be used in the top-level component.

2021-04-03 14:34 UTC, dabralyogesh12 commented on src/features/stall/OrderSent.tsx
> +} from '@material-ui/core/styles';
Done, updated PR, the spacing between Time to prepare and Track Order button will be determined automatically as we need to push this button to the bottom in the mobile screen.

2021-04-03 14:34 UTC, dabralyogesh12 commented on src/features/stall/OrderSent.tsx
> +import Dialog from '@material-ui/core/Dialog';
Done, updated PR.

2021-04-03 14:34 UTC, dabralyogesh12 commented on src/features/stall/OrderSent.tsx
> +import useMediaQuery from '@material-ui/core/useMediaQuery';
Done, updated PR.

2021-04-03 14:35 UTC, dabralyogesh12 commented on src/features/stall/StallMenu.tsx
> +);
Done, updated PR.

2021-04-03 14:39 UTC, dabralyogesh12 commented on src/features/stall/StallMenu.tsx
> +    },
Done, https://github.com/SleekOrg/tracker/issues/304

2021-04-03 14:39 UTC, dabralyogesh12 commented on src/features/stall/StallMenu.tsx
> +);
Done, updated PR.

2021-04-03 14:39 UTC, dabralyogesh12 commented on src/features/stall/StallMenu.tsx
> +      marginTop: theme.spacing(6),
Done, updated PR.

2021-04-03 14:39 UTC, dabralyogesh12 commented on src/features/stall/StallMenu.tsx
> +    },
Done, updated PR.

2021-04-03 14:39 UTC, dabralyogesh12 commented on src/features/stall/StallMenu.tsx
> +const useStyles = makeStyles((theme: Theme) =>
Done, updated PR.

2021-04-03 14:42 UTC, dabralyogesh12 commented on package.json
> +  "name": "OrderAhead",
Corrected that, updated PR.

2021-04-03 14:44 UTC, dabralyogesh12 commented on package.json
> +    "clsx": "^1.1.1",
The font size is the same 16px on the mobile screen.

2021-04-05 04:37 UTC, teamSleek requested changes

2021-04-05 04:37 UTC, teamSleek commented on src/types.tsx
> +}
Logo and white strip has curved corners in figma

![Screen Shot 2021-04-04 at 9 31 00 PM](https://user-images.githubusercontent.com/61997705/113537333-470e9f00-958d-11eb-9772-acbd3f62879b.png)

2021-04-05 04:37 UTC, teamSleek commented on src/types.tsx
> +  type: string;
back button missing. Compare with figma
![Screen Shot 2021-04-04 at 9 33 05 PM](https://user-images.githubusercontent.com/61997705/113537363-5e4d8c80-958d-11eb-9566-e3e748f13287.png)

2021-04-05 04:37 UTC, teamSleek commented on src/types.tsx
> +export interface IPos {
time should be above the text. Compare with figma
![Screen Shot 2021-04-04 at 9 33 57 PM](https://user-images.githubusercontent.com/61997705/113537398-7cb38800-958d-11eb-89bf-ca89eb444762.png)

2021-04-05 04:37 UTC, teamSleek commented on src/theme.tsx
> +        height: 'auto',
Costa coffee is not grounded in mobile. Comapre with figma
![Screen Shot 2021-04-04 at 9 34 38 PM](https://user-images.githubusercontent.com/61997705/113537460-a5d41880-958d-11eb-9300-e7136a1ec473.png)

2021-04-05 04:37 UTC, teamSleek commented on src/features/stall/AddedToCart.tsx
> +                Checkout and Skip The Line for $1.05
font seems off for this text

2021-04-05 06:58 UTC, dabralyogesh12 commented on src/types.tsx
> +}
Done, updated PR.

2021-04-05 06:59 UTC, dabralyogesh12 commented on src/types.tsx
> +  type: string;
I am making this for the place order screen. Will integrate it on this page too.

2021-04-05 06:59 UTC, dabralyogesh12 commented on src/types.tsx
> +export interface IPos {
Done, updated PR.

2021-04-05 06:59 UTC, dabralyogesh12 commented on src/theme.tsx
> +        height: 'auto',
Done, updated PR.

2021-04-05 07:01 UTC, dabralyogesh12 commented on src/features/stall/AddedToCart.tsx
> +                Checkout and Skip The Line for $1.05
I have set the font size here, but the font here is Roboto and I think we need to set Robot for all buttons through the central theme file.

2021-04-05 07:10 UTC, teamSleek commented on src/types.tsx
> +export interface IPos {
extra vertical spacing between 2 min and "skip the line"
![Screen Shot 2021-04-05 at 12 09 44 AM](https://user-images.githubusercontent.com/61997705/113547690-3c5f0480-95a3-11eb-925e-dd634c18cf32.png)

2021-04-05 07:10 UTC, teamSleek commented on src/types.tsx
> +export interface IPos {
@dabralyogesh12

2021-04-05 07:34 UTC, merged