Features/checkout
SleekOrg/orderahead-user-app pull request #6
Opened 2021-04-06 04:54 UTC by aryansingh02

2021-04-06 21:01 UTC, teamSleek requested changes

2021-04-06 21:01 UTC, teamSleek commented on package.json
> +    "@types/styled-components": "^5.1.9",
Let us not migrate all the baggage from last app. Use modal equivalent in material UI and no custom styling as much as possible. If we migrate so much stuff then what is the point of making a new app?

2021-04-06 21:39 UTC, teamSleek requested changes

2021-04-06 21:39 UTC, teamSleek commented on src/App.tsx
> +import Cart from './features/cart/Cart';
Unable to visit /cart
<img width="1617" alt="Screen Shot 2021-04-06 at 2 39 32 PM" src="https://user-images.githubusercontent.com/61997705/113781693-ec3c8b00-96e5-11eb-8a1e-33e0d2661f64.png">

2021-04-06 22:04 UTC, teamSleek commented
Also, link the correct issue.

2021-04-09 12:52 UTC, aryansingh02 commented on package.json
> +    "@types/styled-components": "^5.1.9",
removed all stuff

2021-04-09 20:24 UTC, teamSleek commented
Fix conflict

2021-04-09 21:37 UTC, teamSleek requested changes

2021-04-09 21:37 UTC, teamSleek commented on src/features/cart/Cart.tsx
> +  fetchOrderData = async () => {
all this should be moved to the redux state

2021-04-09 21:37 UTC, teamSleek commented on src/features/cart/Cart.tsx
> +      this.triggerSkipTheLineModal();
there is no modal in new design

2021-04-09 21:37 UTC, teamSleek commented on src/features/cart/Cart.tsx
> +/* eslint no-param-reassign: 0 */ // --> OFF
Delete all unused code. Copying and pasting from the previous app have brought in things that are not relevant in this app. Ideally we should NOT have copy-pasted and we should have coded things from scratch which would have kept things clean. 

https://sourcemaking.com/antipatterns/cut-and-paste-programming

2021-04-09 21:37 UTC, teamSleek commented on src/utils.tsx
> +export const GenerateCurrencyNumber = (price:IPrice) => (
create a component for this.

2021-04-09 21:37 UTC, teamSleek commented on src/utils.tsx
> +export async function CalculateInvoice(cart:ICart) {
why do we even need this function?

2021-04-09 21:37 UTC, teamSleek commented on src/utils.tsx
> +export const DeleteLineItemFromCart = (cart:ICart, lineItemId:string) => {
move all these cart management function in CartSlice or a CartUtil file

2021-04-09 21:37 UTC, teamSleek commented on src/types.tsx
> +export type ICart = typeof cart;
using ICart everywhere and defining it this way seems to be circumventing the entire Typescript checking itself. This was okay as long as we were doing UX and using this for mock data. Doing it for redux state management, API call, and all the data manipulation functions seems wrong.

2021-04-09 21:37 UTC, teamSleek commented on src/features/event/Event.tsx
> +// @ts-ignore
why do we need ts-ignore here? add comment

2021-04-09 21:37 UTC, teamSleek commented on src/features/event/DesktopHeader.tsx
> +              // onClick={handleMobileMenuOpen}
Is this intended?

2021-04-09 21:37 UTC, teamSleek commented on src/features/event/DesktopHeader.tsx
> -  const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null);
why delete all this?

2021-04-09 21:37 UTC, teamSleek commented on src/features/cart/Cart.tsx
> +      invoice: undefined,
Unable to run this.
![Screen Shot 2021-04-09 at 2 35 26 PM](https://user-images.githubusercontent.com/61997705/114243122-e989a200-9940-11eb-9e4e-07d54284d989.png)

2021-04-09 21:37 UTC, teamSleek commented on src/features/cart/Cart.tsx
> +      `${config.get('backend')}/stall/${stall._id}/wait-time`
where is this `backend` param defined ?

2021-04-09 21:37 UTC, teamSleek commented on src/features/cart/Cart.tsx
> +    fetch(`${config.get('backend')}/surge-fee`, {
ditto

2021-04-12 21:01 UTC, teamSleek requested changes
Styling very off in a lot of ways.

As part of the verification, step confirms that your thing matches with Figma. And screenshots of you app on desktop and mobile as proof.

2021-04-12 21:01 UTC, teamSleek commented on src/App.scss
> +.centerJustifiedFlex {
use Material grid and not custom css. Do not import it from the other app.

2021-04-12 21:01 UTC, teamSleek commented on src/App.tsx
> +config.set(configuration, { assign: false, freeze: false });
Tip section is missing.

2021-04-12 21:01 UTC, teamSleek commented on src/features/cart/Cart.tsx
> +              <Typography roboto={true}>Proceed to Checkout</Typography>
styling is off

2021-04-14 02:48 UTC, teamSleek commented on .eslintrc
> +    "react/static-property-placement": "off",
@aryansingh02 It seems that this still an open item?

2021-04-14 02:52 UTC, teamSleek requested changes
The styling and alignment seem to be off in the line items section of the cart.

2021-04-15 03:15 UTC, aryansingh02 commented on src/features/event/DesktopHeader.tsx
> -  const [anchorEl, setAnchorEl] = React.useState<null | HTMLElement>(null);
was not needed

2021-04-15 03:16 UTC, aryansingh02 commented on src/App.scss
> +}
it's not used in grid, used at some places to style boxes.

2021-04-15 23:05 UTC, merged