git commit -m "feat(NewOrderAhead/Order Confirmation): Added the order confirmation screen layout. Also added the Back Button which now will be integrated with other pages too."
SleekOrg/orderahead-user-app pull request #7
Opened 2021-04-06 07:16 UTC by dabralyogesh12

Issues: fixes https://github.com/SleekOrg/tracker/issues/296
git commit -m "feat(NewOrderAhead/Order Confirmation): Added the order confirmation screen layout. Also added the Back Button which now will be integrated with other pages too."
Description: Added the layout for the Order confirmation screen. The font, for now, is picked from the central theme file so can be GT Walsheim somewhere instead of Roboto.
Verification: Tested locally.

2021-04-06 22:02 UTC, teamSleek requested changes

2021-04-06 22:02 UTC, teamSleek commented on src/features/style/style.css
> +.PhoneInputInput {
Can we create a sleek-phone-input-box using react-phone-input-box and use that? we should also scope all following css changes to `sleek-phone-input-box` only.

2021-04-06 22:02 UTC, teamSleek commented on src/features/stall/OrderConfirmation.tsx
> +const useStyles = makeStyles((theme: Theme) =>
The font seems off. Let use the correct font as we build new things as the theme file is now settled.

2021-04-08 12:35 UTC, dabralyogesh12 commented on src/App.tsx
> +              <Route
Done, updated PR.

2021-04-08 12:35 UTC, dabralyogesh12 commented on src/features/style/style.css
> +.PhoneInputInput {
Done, updated PR.

2021-04-08 12:36 UTC, dabralyogesh12 commented on src/features/stall/OrderConfirmation.tsx
> +const useStyles = makeStyles((theme: Theme) =>
Done, updated PR.

2021-04-08 12:36 UTC, dabralyogesh12 commented on src/App.tsx
> +              <Route
Done, updated PR.

2021-04-09 04:55 UTC, teamSleek requested changes

2021-04-09 04:55 UTC, teamSleek commented on package.json
> +    "@types/react-phone-number-input": "^3.0.6",
it seems that package-lock.json is broken? I see no deletion from package.json and but so many lines deleted from package-lock.json

2021-04-09 04:55 UTC, teamSleek commented on src/features/stall/OrderConfirmation.tsx
> +      background: '#6D5CFF',
same concern about color referencing as other pr

2021-04-09 05:31 UTC, dabralyogesh12 commented on src/features/stall/OrderConfirmation.tsx
> +      background: '#6D5CFF',
Done, updated PR.

2021-04-09 06:25 UTC, merged