completed searchview for mobile, no clarity on how it would work on d…
SleekOrg/orderahead-user-app pull request #8
Opened 2021-04-06 15:29 UTC by aryansingh02

description: need clarity on how search button would look on deskotp. Mobile search is working perfectly. Desktop search would have to be implemented via redux store since it's and hoc and it's difficult to pass the data up. Plus need guidance on how to implement recent searches

verification: verified manually on desktop and mobile

2021-04-06 21:52 UTC, teamSleek requested changes

2021-04-06 21:52 UTC, teamSleek commented on src/App.tsx
> +              <Route exact path="/search_view" component={SearchView} />
Since this is just UI. Let us add recent searches as well. We will figure out how we will power that.

<img width="374" alt="Screen Shot 2021-04-06 at 2 43 05 PM" src="https://user-images.githubusercontent.com/61997705/113782059-6ff67780-96e6-11eb-904f-4320d5b2e471.png">

2021-04-06 21:52 UTC, teamSleek commented on src/App.tsx
> +              <Route exact path="/search_view" component={SearchView} />
Notice the color difference in the horizontal line and back arrow for the search input

<img width="1506" alt="Screen Shot 2021-04-06 at 2 44 27 PM" src="https://user-images.githubusercontent.com/61997705/113782164-99170800-96e6-11eb-903f-a9713150e126.png">

2021-04-06 21:52 UTC, teamSleek commented on src/data/testData.js
> -  stalls: [stall, stall2, stall3, stall4, stall, stall2, stall3, stall4],
why revert it?

2021-04-06 21:52 UTC, teamSleek commented on src/features/event/DesktopHeader.tsx
> +    // search: {
why comment all this out?

2021-04-06 21:52 UTC, teamSleek commented on src/features/event/DesktopHeader.tsx
> +    // search: {
nit: Ideally all this clean up should be caught in the verification set of the PR

2021-04-06 21:52 UTC, teamSleek commented on src/App.scss
> +.pointer{
For desktop let us go with the approach I mentioned.  In general, use the OA meeting for this kind of discussion, or feel free to ping.

For this case, let us keep the similar structure as /event link with map on the right. For search results show the search results like the tiles on the left of the map. Along side that, we should show a shortlist of tiles on the map.

2021-04-09 20:24 UTC, teamSleek commented
Fix conflict as well

2021-04-12 20:55 UTC, teamSleek requested changes

2021-04-12 20:55 UTC, teamSleek commented on package.json
> +    "@types/google-maps-react": "^2.0.5",
This doesn't seem like the way we discussed. 
<img width="1652" alt="Screen Shot 2021-04-12 at 1 48 11 PM" src="https://user-images.githubusercontent.com/61997705/114460131-3a460880-9b96-11eb-9e36-ea799a54cd36.png">

2021-04-12 20:55 UTC, teamSleek commented on src/App.scss
> +  align-items: center;
It seems that search is not working. How did you test this in the `verificaton` step? that step is not for copying and pasting in each PR. Please add screenshots proving that you actually verified and it worked for you.

<img width="1720" alt="Screen Shot 2021-04-12 at 1 54 03 PM" src="https://user-images.githubusercontent.com/61997705/114460903-927d0a80-9b96-11eb-83ac-1db3b3f2b080.png">

2021-04-13 21:46 UTC, aryansingh02 commented on src/data/testData.js
> -  stalls: [stall, stall2, stall3, stall4, stall, stall2, stall3, stall4],
because stalls with same id were creating errors while rendering, since id was the unique key

2021-04-14 02:22 UTC, teamSleek requested changes

2021-04-14 02:22 UTC, teamSleek commented on src/utils.tsx
> +const FilterbyTag = (stalls: IStall[], tag: string) =>
Searching for `Coffee` doesn't show Costa Coffee from the dummy content?
<img width="490" alt="Screen Shot 2021-04-13 at 7 20 41 PM" src="https://user-images.githubusercontent.com/61997705/114644950-5a0c2800-9c8d-11eb-9cc6-dca37ff2b13c.png">

2021-04-14 02:22 UTC, teamSleek commented on .eslintrc
> +    // the reason this has been turned to warn because in spite of installing all dependencies somtimes typescript keeps throwing up this error for no reason
can you share an example of the error that you get?

2021-04-14 07:28 UTC, teamSleek commented
Left and right padding disappear on the stall tiles in search result mode. 
<img width="1731" alt="Screen Shot 2021-04-14 at 12 27 51 AM" src="https://user-images.githubusercontent.com/61997705/114670869-4d50f980-9cb8-11eb-92e0-c8aaafc9c707.png">

2021-04-14 07:29 UTC, merged