feat(NewOrderAhead/Order Status Screen): Layout for the order status screen.
SleekOrg/orderahead-user-app pull request #9
Opened 2021-04-07 14:30 UTC by dabralyogesh12

Issues: fixes https://github.com/SleekOrg/tracker/issues/298
feat(NewOrderAhead/Order Status Screen): Layout for the order status screen.
Description: Added the layout for the order status screen. The back button integration is pending and will be done once the Order Confirmation screen PR is pushed.
Verification: Tested locally.

2021-04-07 16:39 UTC, teamSleek requested changes

2021-04-07 16:39 UTC, teamSleek commented on src/features/stall/StatusStepper.tsx
> +function getSteps() {
match states from https://github.com/SleekOrg/SleekRepo/blob/master/user_app/src/components/NewOrderView.js#L107

It seems that you are missing completed_pr and cancelled

2021-04-07 16:39 UTC, teamSleek commented on src/features/stall/OrderStatus.tsx
> +                Detailed receipt
let us center align heading as we discussed.

2021-04-08 14:26 UTC, dabralyogesh12 commented on src/features/stall/OrderStatus.tsx
> +                Detailed receipt
Done, updated PR.

2021-04-08 14:27 UTC, dabralyogesh12 commented on src/features/stall/StatusStepper.tsx
> +function getSteps() {
I have added the status strings.

2021-04-09 04:40 UTC, teamSleek requested changes

2021-04-09 04:40 UTC, teamSleek commented on src/features/stall/OrderStatus.tsx
> +                style={{ color: '#6D5CFF' }}
let us not hardcode color here but use it from the theme i.e. theme's primary color

2021-04-09 04:40 UTC, teamSleek commented on src/features/stall/OrderStatus.tsx
> +                style={{ color: '#6D5CFF' }}
here and everywhere else

2021-04-09 04:40 UTC, teamSleek commented on src/features/stall/OrderStatus.tsx
> +                style={{ color: '#6D5CFF', marginTop: '15px' }}
ditto

2021-04-09 04:40 UTC, teamSleek commented on src/features/stall/StatusStepper.tsx
> +function getSteps() {
can't see it here. Also, delete the collected?
<img width="527" alt="Screen Shot 2021-04-08 at 9 37 01 PM" src="https://user-images.githubusercontent.com/61997705/114129019-8fda9680-98b2-11eb-9f82-e4aa5529ae61.png">

2021-04-09 04:40 UTC, teamSleek commented on src/features/stall/OrderStatus.tsx
> +                Detailed receipt
This doesn't seem like the mobile version we discussed?
<img width="616" alt="Screen Shot 2021-04-08 at 9 39 26 PM" src="https://user-images.githubusercontent.com/61997705/114129198-f069d380-98b2-11eb-90ab-9acd7bf74f0e.png">

2021-04-09 04:40 UTC, teamSleek commented on src/features/stall/OrderStatus.tsx
> +                style={{ color: '#6D5CFF' }}
We should strive to not repeat any styling that is already part of the theme.

2021-04-09 05:30 UTC, dabralyogesh12 commented on src/features/stall/StatusStepper.tsx
> +function getSteps() {
Done, updated PR.

2021-04-09 05:31 UTC, dabralyogesh12 commented on src/features/stall/OrderStatus.tsx
> +                Detailed receipt
Center aligned the Detailed receipt with respect to Order Id.

2021-04-09 05:31 UTC, dabralyogesh12 commented on src/features/stall/OrderStatus.tsx
> +                style={{ color: '#6D5CFF', marginTop: '15px' }}
Done, updated PR.

2021-04-09 06:30 UTC, merged